merge_protections_settings:
  auto_merge_conditions: true

merge_protections:
  - name: "CodeRabbit approval for admin authors"
    if:
      - "base = main"
      - "author = @logica-oss/admin"
    success_conditions:
      - or:
          - "approved-reviews-by = coderabbitai[bot]"
          - "label = force-merge"
  - name: "CodeRabbit and admin approval for contributors"
    if:
      - "base = main"
      - "author != renovate[bot]"
      - "author != @logica-oss/admin"
    success_conditions:
      - "approved-reviews-by = coderabbitai[bot]"
      - "approved-reviews-by = @logica-oss/admin"

pull_request_rules:
  - name: "Request admin review once CodeRabbit approved"
    conditions:
      - "base = main"
      - "author != renovate[bot]"
      - "author != @logica-oss/admin"
      - "approved-reviews-by = coderabbitai[bot]"
      - "-approved-reviews-by = @logica-oss/admin"
    actions:
      request_reviews:
        teams:
          - "admin"

queue_rules:
  - name: "renovate"
    merge_method: "squash"
    queue_conditions:
      - "base = main"
      - "author = renovate[bot]"
  - name: "default"
    merge_method: "merge"
    queue_conditions:
      - "base = main"
      - "author != renovate[bot]"
