name: Check (Release Label)

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened, ready_for_review]

concurrency:
  group: check-release-label-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-release-label:
    name: Check (Release Label)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read # Read PR labels for the release label check
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check release label
        uses: logica-oss/actions-toolkit/check-release-label@3caa6b132a2307a0dcbff102d1d1411a2be4107a # v1.0.1
