name: Verify (Actions)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: verify-actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-actions:
    name: Verify (Actions)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Verify actions
        uses: logica-oss/actions-toolkit/verify-actions@3caa6b132a2307a0dcbff102d1d1411a2be4107a # v1.0.1
